"""
GitHub Actions Terraform workflow generator.

Builds `.github/workflows/terraform.yml` for a repo this tool pushes into —
the piece that was explicitly scoped out of the earlier "production ready"
work (real remote state backend + diagram-diff-in-PRs were built first, as
prerequisites; the workflow itself was deferred). Two decisions were already
made in that earlier conversation and are implemented here as-is:

  1. AWS auth via OIDC (recommended over static long-lived access keys) —
     `aws-actions/configure-aws-credentials` assumes a role via
     `role-to-assume: ${{ vars.AWS_OIDC_ROLE_ARN }}`, a repo/org-level
     variable (not a secret — role ARNs aren't sensitive) the user must set
     once after creating the trust relationship on the AWS side. This tool
     has no way to create that IAM role/OIDC provider itself (it would need
     real AWS credentials with IAM-write access, which is exactly the kind
     of broad permission this whole feature exists to avoid needing) — the
     generated workflow's header comment says so explicitly rather than
     silently failing on first run with no explanation.

  2. Auto-apply on merge, gated by required reviewers — implemented via
     GitHub's native per-job `environment:` key (one GitHub Environment per
     Terraform environment: dev/staging/prod), NOT a third-party gating
     action. The user still has to configure each Environment's required-
     reviewers protection rule once in repo Settings — this tool can create
     the workflow but can't grant itself repo-admin to configure branch/
     environment protection rules unattended, so, same as the OIDC role,
     that one-time setup step is documented rather than silently assumed.

Directory-per-environment (see github_pusher.py's own docstring for why that
convention exists) means one `terraform/<environment>/` folder per
environment, all under the SAME repo/default branch. This generator matrix-
es both the `plan` (on pull_request) and `apply` (on push to default branch)
jobs over the known environment list, running each with
`working-directory: terraform/<environment>`.

Deliberately NOT using a third-party "detect changed paths" action (e.g.
dorny/paths-filter) to skip unaffected environments — every matrix entry
always runs `plan`/`apply` regardless of which environment's files actually
changed in a given push. This trades some CI minutes (an unmodified
environment's `plan` just reports "No changes") for not depending on a
marketplace action's exact behavior, which can't be verified against a real
GitHub Actions runner from this sandbox. Worth revisiting if CI cost becomes
a real concern.
"""

from __future__ import annotations

DEFAULT_ENVIRONMENTS = ["dev", "staging", "prod"]
DEFAULT_TERRAFORM_VERSION = "1.9.0"


def generate_terraform_workflow(
    default_branch: str,
    aws_region: str = "us-east-1",
    environments: list[str] | None = None,
    tf_subdir: str = "terraform",
    terraform_version: str = DEFAULT_TERRAFORM_VERSION,
) -> str:
    """
    Returns the full YAML text for `.github/workflows/terraform.yml`.

    Regenerated fresh on every push this tool makes (same path, same
    base_tree-merge mechanism as the Terraform/diagram files) — if the repo
    owner hand-edits this file afterward, the next push from this tool will
    overwrite those edits. Documented in the generated file's own header
    comment and in the PR body, not silently overwritten without warning.
    """
    envs = environments or DEFAULT_ENVIRONMENTS
    env_list_yaml = "\n".join(f"          - {e}" for e in envs)

    return f"""\
# Auto-generated by arch2terraform on every push to this repo — hand edits
# here will be overwritten on the next push. If you need to customize this
# workflow, consider forking it to a differently-named file instead.
#
# ONE-TIME SETUP REQUIRED before this workflow will actually run successfully:
#
#   1. Create an AWS IAM OIDC identity provider for GitHub Actions (if you
#      don't already have one) and an IAM role that trusts it, scoped to
#      this repo. AWS's own guide:
#      https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
#      This tool cannot create that role itself — doing so would need
#      broad IAM-write AWS credentials, which defeats the point of moving
#      to scoped OIDC auth in the first place.
#   2. Set a repository (or organization) variable named AWS_OIDC_ROLE_ARN
#      to that role's ARN (Settings -> Secrets and variables -> Actions ->
#      Variables). It's a variable, not a secret - role ARNs aren't
#      sensitive, only the temporary credentials assumed via them are.
#   3. Create a GitHub Environment (Settings -> Environments) for each of:
#{chr(10).join(f"#        - {e}" for e in envs)}
#      and add required reviewers to whichever environments should gate
#      apply behind manual approval (typically staging/prod; dev is often
#      left ungated). This is what actually enforces "auto-apply on merge,
#      gated by required reviewers" - the workflow below just references
#      these environments by name, GitHub enforces the gate.
#
# Until all three are done, the `plan` job's AWS auth step will fail with a
# clear "role not found" / "vars.AWS_OIDC_ROLE_ARN is empty" style error -
# that's expected, not a bug in this workflow.

name: Terraform

on:
  pull_request:
    paths:
      - "{tf_subdir}/**"
  push:
    branches:
      - {default_branch}
    paths:
      - "{tf_subdir}/**"

# id-token: write is required for OIDC AWS auth (no static access keys are
# ever stored in this repo). pull-requests: write lets the plan job comment
# results back onto the PR.
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  plan:
    name: terraform plan (${{{{ matrix.environment }}}})
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment:
{env_list_yaml}
    defaults:
      run:
        working-directory: {tf_subdir}/${{{{ matrix.environment }}}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{{{ vars.AWS_OIDC_ROLE_ARN }}}}
          aws-region: {aws_region}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "{terraform_version}"

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Plan
        run: terraform plan -input=false -no-color

  apply:
    name: terraform apply (${{{{ matrix.environment }}}})
    if: github.event_name == 'push' && github.ref == 'refs/heads/{default_branch}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment:
{env_list_yaml}
    # Ties this job to the matching GitHub Environment - required reviewers
    # configured there (one-time setup, see header comment) is what actually
    # gates the apply, not anything in this workflow file itself.
    environment: ${{{{ matrix.environment }}}}
    defaults:
      run:
        working-directory: {tf_subdir}/${{{{ matrix.environment }}}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{{{ vars.AWS_OIDC_ROLE_ARN }}}}
          aws-region: {aws_region}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "{terraform_version}"

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve
"""
