"""
Packager Service
-----------------
Takes a completed TerraformPlan + ValidationResult and:
  1. Writes all .tf files into a structured output directory
  2. Generates a README.md with resource summary, usage instructions,
     validation results, and architecture notes
  3. Zips everything into a downloadable archive
"""
from __future__ import annotations
import os
import shutil
import zipfile
import logging
import tempfile
from datetime import datetime
from pathlib import Path

log = logging.getLogger(__name__)

import sys
# services/packager/packager.py -> packager(0)/services(1)/app(2)/backend(3)/
# arch2tf-product(4). Was parents[5] (one level too far, lands on "thesis") —
# pre-existing bug, same class as missing_info_detector.py's.
sys.path.insert(0, str(Path(__file__).resolve().parents[4]))
from shared.schemas.models import (
    TerraformPlan, ValidationResult, ValidationStatus, ParsedDiagram, Job
)
from app.core.storage import save_output_dir, get_output_path, read_upload
from app.core.config import get_settings

_s = get_settings()


async def package_output(job: Job) -> tuple[str, str]:
    """
    Build the ZIP archive and README.
    Returns (zip_path, readme_content).
    """
    plan = job.terraform_plan
    validation = job.validation_result
    parsed = job.parsed_diagram

    with tempfile.TemporaryDirectory(prefix="arch2tf_pkg_") as tmpdir:
        output_root = Path(tmpdir) / "terraform"
        output_root.mkdir()

        # ── Write root module files ──────────────────────────────────────────
        for filename, content in plan.root_module_files.items():
            (output_root / filename).write_text(content, encoding="utf-8")

        # ── Write child modules ──────────────────────────────────────────────
        for module in plan.modules:
            mod_dir = output_root / "modules" / module.name
            mod_dir.mkdir(parents=True, exist_ok=True)
            for filename, content in module.files.items():
                (mod_dir / filename).write_text(content, encoding="utf-8")

        # ── Generate README ──────────────────────────────────────────────────
        readme = _generate_readme(plan, validation, parsed, job)
        readme_path = output_root / "README.md"
        readme_path.write_text(readme, encoding="utf-8")

        # ── Generate .terraform-version pinning file ─────────────────────────
        (output_root / ".terraform-version").write_text("1.6.0\n")

        # ── Checkov config: suppress one confirmed false positive ────────────
        # Real finding, 2026-07-24: every security group this pipeline
        # generates IS attached to its owning resource - either a
        # same-module `aws_security_group.X.id` reference, or (when the
        # owning resource lands in a different module) a real
        # var./output/module-argument cross-module wire (see
        # terraform_planner.py's _wire_sg_attachments). Verified with an
        # isolated 2-module repro: Checkov's CKV2_AWS_5 graph check cannot
        # trace an attribute reference through a module-boundary variable
        # back to the security group resource that populates it, so it
        # reports every cross-module-attached SG as unattached even though
        # `terraform plan` shows the real attachment. An inline
        # `#checkov:skip=CKV2_AWS_5` comment does NOT suppress this specific
        # graph check inside a child module (confirmed by testing) - only a
        # discovered `.checkov.yaml` config does, hence this file instead of
        # a code comment.
        checkov_config = (
            "# Generated by arch2terraform - do not edit manually\n"
            "#\n"
            "# CKV2_AWS_5 (\"Security Groups are attached to another\n"
            "# resource\") is skipped here because every security group this\n"
            "# pipeline generates IS attached - either directly in its own\n"
            "# module, or via real cross-module Terraform variable wiring\n"
            "# when the owning resource lives in a different module (see\n"
            "# modules/*/main.tf for the vpc_security_group_ids /\n"
            "# security_groups references, and this project's root main.tf\n"
            "# for the module-argument wiring that supplies them). Checkov's\n"
            "# static graph resolver cannot trace an attribute reference\n"
            "# through a module-boundary variable, so it reports these as\n"
            "# unattached even though they genuinely are not - a confirmed\n"
            "# tool limitation, not a real security gap.\n"
            "skip-check:\n"
            "  - CKV2_AWS_5\n"
        )
        (output_root / ".checkov.yaml").write_text(checkov_config, encoding="utf-8")

        # ── Generate Makefile for convenience ────────────────────────────────
        makefile = _generate_makefile()
        (output_root / "Makefile").write_text(makefile, encoding="utf-8")

        # ── Bundle the state file + plan output + diagram "intact" alongside
        # the generated modules (her explicit request, 2026-07-08) ───────────
        # State file: only ever placed in this LOCAL download — never pushed
        # to GitHub (her call, same day: state can carry sensitive resource
        # attributes that shouldn't enter git history). Sits right next to
        # the root module files, matching where a real local state file
        # would conventionally live relative to the config it corresponds to.
        if job.state_file_path:
            try:
                state_bytes = await read_upload(job.state_file_path)
                (output_root / "terraform.tfstate").write_bytes(state_bytes)
            except Exception:
                log.warning("Could not read uploaded state file for job %s while packaging", job.job_id, exc_info=True)

        # Real captured `terraform plan` output (when the sandbox check ran
        # one) as a plain text file — the same content already shown in the
        # UI's "Terraform Plan Output" panel, now downloadable alongside the
        # code it was generated from instead of only living in the job's
        # in-memory ValidationResult.
        if validation and validation.terraform_plan_output:
            (output_root / "terraform-plan-output.txt").write_text(
                validation.terraform_plan_output, encoding="utf-8"
            )

        # The source architecture diagram itself — previously only ever
        # pushed to GitHub (diagrams/<environment>/<filename>), never part
        # of the local download. Bundling it here means the ZIP alone is a
        # complete, self-contained record: the diagram that drove this
        # generation, the Terraform it produced, what it was validated
        # against, and (if uploaded) the state it was diffed against.
        if job.file_path and job.original_filename:
            try:
                diagram_bytes = await read_upload(job.file_path)
                diagram_dir = output_root / "diagram"
                diagram_dir.mkdir(exist_ok=True)
                (diagram_dir / job.original_filename).write_bytes(diagram_bytes)
            except Exception:
                log.warning("Could not read source diagram for job %s while packaging", job.job_id, exc_info=True)

        # vars.yaml — every clarification answer this job ended up with
        # (whether asked from scratch or reused from a previously-uploaded
        # vars.yaml), see missing_info_detector.generate_vars_yaml(). Unlike
        # terraform.tfstate, this is config (sizes/engines/CIDRs), not
        # secrets — her call, 2026-07-08 — so it's fine to also push to
        # GitHub (see github_pusher.py), not local-ZIP-only. Re-uploading
        # this same file as `vars_file` on a future run against an updated
        # diagram skips re-asking everything it already covers.
        if job.generated_vars_yaml:
            (output_root / "vars.yaml").write_text(job.generated_vars_yaml, encoding="utf-8")

        # ── Zip everything ───────────────────────────────────────────────────
        zip_base = Path(_s.local_output_dir) / job.job_id / "terraform_output"
        zip_base.parent.mkdir(parents=True, exist_ok=True)
        zip_path = shutil.make_archive(str(zip_base), "zip", tmpdir, "terraform")

    log.info("Packaged output for job %s → %s", job.job_id, zip_path)
    return zip_path, readme


def _generate_readme(
    plan: TerraformPlan,
    validation: ValidationResult | None,
    parsed: ParsedDiagram | None,
    job: Job,
) -> str:
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# Terraform Infrastructure",
        "",
        f"> Generated by **arch2terraform** on {now}  ",
        f"> Source diagram: `{job.original_filename}`  ",
        f"> Source format: `{job.diagram_format}`",
        "",
        "## Package contents",
        "",
        "- `modules/`, root `.tf` files — the generated Terraform",
        "- `diagram/` — the exact source architecture diagram this package was generated from",
        "- `terraform-plan-output.txt` — the real `terraform plan` output captured during validation (if the sandbox check ran one)",
        "- `vars.yaml` — every config value this job was built with (sizes, engines, CIDRs, etc.), keyed by resource "
        "and field. Re-upload this alongside a future revision of the same diagram to skip re-answering anything it "
        "already covers — only genuinely new/changed fields will be asked about.",
    ]
    if job.state_file_path:
        lines += [
            "- `terraform.tfstate` — the existing state file you uploaded, used to compute real drift for this package",
            "",
            "  **Handle this file with care.** Terraform state can contain plaintext resource attribute values —",
            "  marking a variable `sensitive = true` only hides it from CLI output, it does NOT keep it out of state.",
            "  Treat this file the same way you'd treat your real backend's state: don't commit it to a public repo,",
            "  don't share it casually. It was never pushed to GitHub by this tool — only bundled here, locally.",
        ]
    lines += [
        "",
        "---",
        "",
        "## Architecture Summary",
        "",
    ]

    # Resource type table
    if parsed and parsed.resource_type_summary:
        lines += [
            "| AWS Resource Type | Count |",
            "|---|---|",
        ]
        for rt, count in sorted(parsed.resource_type_summary.items()):
            lines.append(f"| `{rt}` | {count} |")
        lines.append("")

    lines += [
        f"**Total resources:** {plan.resource_count}  ",
        f"**Modules:** {len(plan.modules)}",
        "",
        "---",
        "",
        "## Module Structure",
        "",
        "```",
        ".",
        "├── main.tf              # Root module — wires child modules",
        "├── variables.tf         # Input variables",
        "├── outputs.tf           # Root outputs",
        "├── versions.tf          # Provider version constraints",
        "├── locals.tf            # Computed locals & common tags",
        "├── backend.tf           # Remote state config (uncomment to use)",
    ]
    if "ci_state_access_policy.tf" in plan.root_module_files:
        lines.append("├── ci_state_access_policy.tf  # Least-privilege IAM policy for CI state access (not auto-attached)")
    lines += [
        "├── Makefile             # Convenience commands",
        "└── modules/",
    ]
    for mod in plan.modules:
        lines.append(f"    └── {mod.name}/    # {mod.description}")
    lines += ["```", ""]

    # Module details
    lines += ["## Module Details", ""]
    for mod in plan.modules:
        lines += [
            f"### `modules/{mod.name}`",
            f"{mod.description}",
            "",
            f"**Resources ({len(mod.source_resources)}):**",
        ]
        if parsed:
            for rid in mod.source_resources:
                r = next((x for x in parsed.resources if x.id == rid), None)
                if r:
                    lines.append(f"- `{r.aws_resource_type}.{r.logical_name}` — {r.label}")
        lines.append("")

    # Validation results
    lines += [
        "---",
        "",
        "## Validation Results",
        "",
    ]
    if validation:
        badge = {
            ValidationStatus.PASSED: "✅ PASSED",
            ValidationStatus.WARNING: "⚠️ WARNINGS",
            ValidationStatus.FAILED: "❌ FAILED",
        }.get(validation.overall_status, "UNKNOWN")

        lines += [
            f"**Overall status:** {badge}",
            "",
            f"- ✅ Passed: {validation.passed_count}",
            f"- ⚠️ Warnings: {validation.warning_count}",
            f"- ❌ Errors: {validation.failed_count}",
            "",
        ]
        if validation.checks:
            lines += ["| Check | Tool | Status | Message |", "|---|---|---|---|"]
            for check in validation.checks:
                icon = {"passed":"✅","failed":"❌","warning":"⚠️"}.get(check.status, "ℹ️")
                short_msg = (check.message[:60] + "…") if len(check.message) > 60 else check.message
                lines.append(f"| {check.name} | {check.tool} | {icon} | {short_msg} |")
        lines.append("")
    else:
        lines += ["Validation was not run.", ""]

    # Usage
    lines += [
        "---",
        "",
        "## Usage",
        "",
        "### Prerequisites",
        "",
        "- [Terraform](https://developer.hashicorp.com/terraform/install) >= 1.5.0",
        "- [AWS CLI](https://aws.amazon.com/cli/) configured with appropriate credentials",
        "- AWS account with sufficient permissions",
        "",
        "### Quick Start",
        "",
        "```bash",
        "# 1. Configure AWS credentials",
        "export AWS_ACCESS_KEY_ID=your-key",
        "export AWS_SECRET_ACCESS_KEY=your-secret",
        "export AWS_DEFAULT_REGION=us-east-1",
        "",
        "# 2. Initialise Terraform",
        "terraform init",
        "",
        "# 3. Review the plan",
        "terraform plan",
        "",
        "# 4. Apply (creates resources in your AWS account)",
        "terraform apply",
        "```",
        "",
        "Or use the included `Makefile`:",
        "",
        "```bash",
        "make init     # terraform init",
        "make plan     # terraform plan",
        "make apply    # terraform apply -auto-approve",
        "make destroy  # terraform destroy",
        "```",
        "",
        "### Placeholder values",
        "",
        "Resource attributes that couldn't be inferred from the diagram are filled",
        "with obviously-fake-but-schema-valid placeholders (e.g. `ami-00000000000000000`,",
        "`replace-with-globally-unique-name`, `arn:aws:iam::000000000000:role/REPLACE_WITH_ROLE_NAME`)",
        "so `terraform validate` passes, but `terraform apply` will still need real",
        "values. Find them with:",
        "",
        "```bash",
        'grep -rn "REPLACE_WITH\\|replace-with\\|00000000000" .',
        "```",
        "",
        "### Overriding required values without editing generated code",
        "",
        "Values the upload wizard asked you about (AMI, instance type, DB engine,",
        "storage size, CIDR blocks, etc.) are **not** hardcoded in the generated",
        "`.tf` files — each one is a real Terraform `variable` (see each module's",
        "`variables.tf`) with your answer as its `default`. Change one later by",
        "adding a `terraform.tfvars` file rather than hand-editing `main.tf`:",
        "",
        "```hcl",
        "# terraform/modules/compute/terraform.tfvars",
        'ami = "ami-0123456789abcdef0"',
        "```",
        "",
        "Two or more resources of the same type that need genuinely *different*",
        "values (e.g. a VPC and a subnet both needing `cidr_block`) get",
        "disambiguated variable names automatically (`cidr_block`,",
        "`cidr_block_public_subnet`, ...) so they never collide or overwrite",
        "each other — check each module's `variables.tf` for the exact names.",
        "",
        "---",
        "",
        "## Auto-generated security groups & IAM policies",
        "",
        "You never need to draw an explicit security-group or IAM-role node for",
        "this to work. Every diagram connection between two resources is analyzed",
        "for what kind of traffic it represents:",
        "",
        "- **Network traffic** (e.g. ALB → EC2 → RDS) becomes real security-group",
        "  ingress/egress rules — see each module's `generated_security_groups.tf`.",
        "  Protocol/port is inferred from the edge's label first (\"PostgreSQL\" →",
        "  5432), then the target resource's type and metadata (an RDS node with",
        "  `engine: postgres` → 5432 even with no label at all).",
        "- **AWS-API traffic** (e.g. EC2 → S3, Lambda → SQS) becomes a real",
        "  least-privilege IAM policy on that resource's role instead — see the",
        "  `security/` module's `generated_iam_roles.tf`. Only the specific actions",
        "  that connection needs are granted (e.g. `s3:GetObject`/`s3:PutObject`,",
        "  not `s3:*`).",
        "- Each compute resource that has at least one AWS-API connection gets its",
        "  own IAM role (not a shared one) with a real instance-profile/execution-role",
        "  attachment set directly on the resource — a `NOTE:` comment marks where",
        "  the reference comes from, same convention as cross-module containment",
        "  wiring below.",
        "",
        "---",
        "",
        "## Known limitations",
        "",
        "- **Cross-module containment wiring is automated.** When a diagram shows",
        "  one resource nested inside another (e.g. an EC2 instance inside a subnet)",
        "  and both land in the *same* Terraform module, the reference is wired",
        "  directly (e.g. `subnet_id = aws_subnet.x.id`). When they land in",
        "  *different* modules (e.g. the instance in `compute/`, the subnet in",
        "  `networking/`), the wiring is still real — the parent module gets an",
        "  `output` for the referenced resource's `id`, the child module gets a",
        "  matching `variable`, and the root `main.tf` passes it through the module",
        "  call. A `NOTE:` comment above the resource block documents where each",
        "  cross-module value comes from — search for `NOTE:` if you want to see",
        "  all of them:",
        "",
        "  ```bash",
        '  grep -rn "NOTE:" .',
        "  ```",
        "",
        "- **Passwords & secrets:** resources needing a master password (RDS, Aurora,",
        "  Redshift) use the provider's `manage_master_user_password` option instead",
        "  of a literal password value, so no secret ever appears in generated code —",
        "  AWS Secrets Manager creates and stores it automatically on `apply`. AmazonMQ",
        "  brokers (no AWS-managed-secret option exists for that resource type) get an",
        "  auto-generated `random_password` stored in Secrets Manager instead — see the",
        "  `random_password`/`aws_secretsmanager_secret` resources next to the broker.",
        "- **AMI IDs:** EC2 AMI IDs are region-specific. Find the correct one for",
        "  your region at: https://aws.amazon.com/amazon-linux-ami/",
        "- **Backend state:** The `backend.tf` file contains a commented-out S3",
        "  remote state config. Uncomment and configure it for team use.",
        "- **CI state access policy:** when a real state backend IS configured,",
        "  `ci_state_access_policy.tf` generates a least-privilege `aws_iam_policy`",
        "  scoped to only this project's state objects and lock table — it is NOT",
        "  attached to anything automatically. Attach it yourself to whichever IAM",
        "  role/user your CI pipeline runs as.",
        "",
        "---",
        "",
        "*Generated by [arch2terraform](https://github.com/your-org/arch2terraform)*",
        "",
    ]

    return "\n".join(lines)


def _generate_makefile() -> str:
    return """.PHONY: init plan apply destroy fmt validate

init:
\tterraform init

plan:
\tterraform plan -out=tfplan

apply:
\tterraform apply tfplan

apply-auto:
\tterraform apply -auto-approve

destroy:
\tterraform destroy -auto-approve

fmt:
\tterraform fmt -recursive

validate:
\tterraform validate

clean:
\trm -rf .terraform tfplan .terraform.lock.hcl

# Show all TODO items that need manual input
todos:
\t@grep -rn "# TODO:" . --include="*.tf" | sed 's/^/  /'
"""
